### ISSUE TITLE
Improve release flow

### ISSUE THREAD

**Issue by peaceiris** [abema/github-actions-merger#31]
https://github.com/abema/github-actions-merger/blob/c3bf754d20f5cf6ee47a7970705d14da4a93e108/action.yml#L9

```yaml
runs:
  using: 'docker'
  image: 'docker://abema/github-actions-merger@v1.x.x'
```
